name: hamo_pharmacy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.2.1
  firebase_core: null
  firebase_auth: null
  firebase_storage: null
  flutter_bloc: null
  device_preview: null
  provider: null
  intl_phone_number_input: ^0.7.0+2
  smooth_page_indicator: null
  font_awesome_flutter: null
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.0
  pdf: ^3.11.1
  shared_preferences:
  printing:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_gen_runner: null
  build_runner: null

flutter:
  assets:
    - assets/
flutter_gen:
  output: lib/gen/
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
